### ISSUE TITLE
Profile page showing fields that should not be there

### ISSUE THREAD

**Issue by ssingh1997** [gcivil-nyu-org/Team_Team2_CS-GY-6063-Fall2021#159]
**IGNORE**
On the User Profile page I am seeing fields such as accessible, family-friendly, and transaction not required. These should not be there for the user I believe.

**PENDING ISSUE STILL:**
I am also unable to see the search from the profile page

**Comment by ssingh1997** [comment]
I just remembered you explained this yesterday, my apologies!

**Comment by SimonYSC** [comment]
No worries. Just for clarification, those in the profile page are so-called "user preference". However, your feedback reminded me that there should be a title or instruction for those preference options so that the user can be more clear about what those options are for. Thanks!
Also, do you mind elaborating on what do you mean by seeing search from the profile page?
If you meant to see your ratings/comments on your profile page, you will need to rate at least one restroom to see it showing in your profile page.
Thanks for your feedback. Let me know if there's more question.

**Comment by ssingh1997** [comment]
Hi Simon, no problem! 

What I meant by the search in the profile page is that I don't see the search in the navbar on the profile page of the user.

![image](https://user-images.githubusercontent.com/39809317/142460580-f7022902-cecf-429b-82bf-17a33cb2aabf.png)

I was just thinking that if the user wanted to go search for a place, they would have to go back to the Home Page to access it. It would be easier to have the search in the navbar on all the pages, including the profile page. Hope this helps!

**Comment by SimonYSC** [comment]
Hey Satyen, thanks again for your feedback. We've updated the UI of the entire website, including the profile page. Now those amenities options have a title "Preference", hopefully it'll be more clear for the user.
